### ISSUE TITLE
Cannot read property 'createElement' of null

### ISSUE THREAD

**Issue by alcferreira** [ljharb/html-element-map#2] opened 2019-03-11 20:18 UTC
It happens on `getTagConstructor` function when document is `null`

**Comment by ljharb** [comment] 2019-03-11 21:24
When is `document` `null`? In a browser, it's always an object, and in node, it should be `undefined`. The implication is that you're doing some improper test cleanup that does `document = null` instead of `delete global.document`?

**Comment by alcferreira** [comment] 2019-03-12 12:25
I was trying to reproduce on a new repo, but I couldn't reproduce it. 
I'll dig deeper in my project to try to find out what happened, but I guess you're right about it because running only this test case it works just fine.

But here's what i got:
I'm working on a react project with jest + enzyme for testing - and updating enzyme (which now uses html-element-map)

We have a test that calls a promise on `componentDidMount`. Let's say this component renders a spinner indicating a loading state. Once the promise resolves, we render other component.

So we have this:

```js
it('should render spinner when it is loading data', () => {
  const onLoadData = jest.fn().mockResolvedValue();

  const wrapper = shallow(
    <CachedDummy cache={new Model()} onLoadData={onLoadData} />
  );

  // renders spinner while data is loading
  expect(wrapper.find('Spinner')).toHaveLength(1);
  expect(wrapper.find('DummyComponent')).toHaveLength(0);
  expect(onLoadData).toBeCalled();

  setImmediate(() => {
    // Error happens here
    expect(wrapper.find('Spinner')).toHaveLength(0); 
    expect(wrapper.find('DummyComponent')).toHaveLength(1);
  });
});
```

I managed to workaround this by doing this: 
```js
await new Promise(setImmediate);

expect(wrapper.find('Spinner')).toHaveLength(0);
expect(wrapper.find('DummyComponent')).toHaveLength(1);
```

Thanks by your input :)

**Comment by ljharb** [comment] 2019-03-12 15:41
Since onLoadData returns a promise, i assume you could `await onLoadData`?

Either way it seems like it’s likely a race condition, and you have some test teardown code setting document to null.

**Comment by ljharb** [comment] 2019-11-19 19:30
Closing until it can be reliably reproduced.

**Closed as completed** 2019-11-19 19:29 UTC

**Comment by hingermayank** [comment] 2020-01-23 09:06
@ljharb @alcferreira I am facing the same issue. It was working fine for me for Node v8.15.0. Recently I switched to node 10.18.1 and it has started failing. I am using Enzyme: 3.9.0 and jest: 24.8.0

**Comment by ljharb** [comment] 2020-01-23 16:47
@hingermayank can you provide a repro repo? Happy to reopen this if so.
